apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-challenge
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: ''
      jsonPointers:
        - /data
      kind: ConfigMap
  project: default
  source:
    path: k8s/.
    repoURL: https://github.com/ioannis-matzaris/pipeline-challenge.git
    targetRevision: fix-updating-image
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
