---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-challenge
  name: pipeline-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-challenge
  template:
    metadata:
      labels:
        app: pipeline-challenge
    spec:
      containers:
        - image: ghcr.io/ioannis-matzaris/pipeline-challenge:main-ebdf577
          name: pipeline-challenge
