# name: CD

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed
#   push:
#     branches: [ '**' ]
#   pull_request:
#     branches: [ '**' ]

# jobs:
#   build-and-push-docker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Generate Docker Tag
#         uses: ./.github/actions/generate-docker-tag

#       - name: Build Docker Image
#         run: docker build -t ghcr.io/${{ github.repository }}:${COMMIT_ID} .

#       - name: Log in to GHCR
#         uses: ./.github/actions/ghcr-login
#         with:
#           password: ${{ secrets.GH_PAT }}

#       - name: Push Docker Image
#         run: docker push ghcr.io/${{ github.repository }}:${COMMIT_ID}
