name: Pipeline Challenge

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker Image Tag
        run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Java tests with Gradle in JDK 25 Container
        run: |
          docker run --rm \
            -v ${PWD}:/workspace \
            -w /workspace \
            gradle:9.2.1-jdk25-alpine \
            ./gradlew :app:test

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:${COMMIT_ID} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${COMMIT_ID}

      - name: Push Prod Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}:main-${COMMIT_ID}
