name: Gradle
on:
  workflow_call:
    inputs:
      gradle-task:
        required: true
        type: string

jobs:
  gradle:
    runs-on: ubuntu-latest
    container:
      image: gradle:9.2.1-jdk25-alpine  # defined once here
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew ${{ inputs.gradle-task }}
