name: Pipeline Challenge

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker image tag
        run: echo "COMMIT_ID=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Java tests with Gradle in JDK 25 container
        run: |
          docker run --rm \
            -v ${PWD}:/workspace \
            -w /workspace \
            gradle:9.2.1-jdk25-alpine \
            ./gradlew :app:test

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${COMMIT_ID} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ github.repository }}:${COMMIT_ID} ghcr.io/${{ github.repository }}:${COMMIT_ID}
          docker push ghcr.io/${{ github.repository }}:${COMMIT_ID}

      - name: Extra step for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Running main-branch only tasks"
