name: pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  run-unit-tests:
    uses: ./.github/workflows/gradle.yml
    with:
      gradle-task: ":app:test"

  build-jar:
    uses: ./.github/workflows/gradle.yml
    with:
      gradle-task: "build"

  build-docker:
      needs:
      - run-unit-tests
      - build-jar
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generate-docker-tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=${{ runner.temp }}/app.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ runner.temp }}/app.tar



  push-docker:
    if: github.ref == 'refs/heads/main'
    needs: 
      - build-docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generate-docker-tag

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ${{ runner.temp }}


      - name: Import Docker image
        run: |
          docker import ${{ runner.temp }}/app.tar "ghcr.io/${{ github.repository }}:${COMMIT_ID}"

      - name: Log in to GHCR
        uses: ./.github/actions/ghcr-login
        with:
          password: ${{ secrets.GH_PAT }}

      - name: Push Docker Image
        run: docker push "ghcr.io/${{ github.repository }}:${COMMIT_ID}"
