name: pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  run-unit-tests:
    uses: ./.github/workflows/gradle.yml
    with:
      gradle-task: ":app:test"

  build-jar:
    uses: ./.github/workflows/gradle.yml
    with:
      gradle-task: "build"

  build-docker:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generate-docker-tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=${{ runner.temp }}/${{ github.repository }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${COMMIT_ID}
          path: ${{ runner.temp }}/${{ github.repository }}.tar



  push-docker:
    # if: github.ref == 'refs/heads/main'
    needs: 
      - unit-test
      - build-jar
      - build-docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/generate-docker-tag

      # - name: Build Docker Image
      #   run: docker build -t "ghcr.io/${{ github.repository }}:${COMMIT_ID}" .

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${ github.repository }
          path: ${{ runner.temp }}

      - name: Log in to GHCR
        uses: ./.github/actions/ghcr-login
        with:
          password: ${{ secrets.GH_PAT }}

      - name: Push Docker Image
        run: docker push "ghcr.io/${{ github.repository }}:${COMMIT_ID}"
